In [2]:
import numpy as np

def tridiag_toeplitz(n, a, b=-1.0):
    A = np.zeros((n, n))
    i = np.arange(n)
    A[i, i] = a
    A[i[1:], i[:-1]] = b
    A[i[:-1], i[1:]] = b
    return A

def kappa2(A):
    # For symmetric A, 2-norm condition number is ratio of extreme eigenvalues
    w = np.linalg.eigvalsh(A)
    return float(max(abs(w)) / min(abs(w)))

n = 6
for a in [1.82, 1.85, 2.0, 2.5, 3.0, 5.0, 10.0]:
    A = tridiag_toeplitz(n, a, b=-1.0)
    print(a, kappa2(A))
    print(A)

1.82 200.52512224768702
[[ 1.82 -1.    0.    0.    0.    0.  ]
 [-1.    1.82 -1.    0.    0.    0.  ]
 [ 0.   -1.    1.82 -1.    0.    0.  ]
 [ 0.    0.   -1.    1.82 -1.    0.  ]
 [ 0.    0.    0.   -1.    1.82 -1.  ]
 [ 0.    0.    0.    0.   -1.    1.82]]
1.85 75.98347262575423
[[ 1.85 -1.    0.    0.    0.    0.  ]
 [-1.    1.85 -1.    0.    0.    0.  ]
 [ 0.   -1.    1.85 -1.    0.    0.  ]
 [ 0.    0.   -1.    1.85 -1.    0.  ]
 [ 0.    0.    0.   -1.    1.85 -1.  ]
 [ 0.    0.    0.    0.   -1.    1.85]]
2.0 19.195669358089226
[[ 2. -1.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0. -1.  2.]]
2.5 6.162684844116026
[[ 2.5 -1.   0.   0.   0.   0. ]
 [-1.   2.5 -1.   0.   0.   0. ]
 [ 0.  -1.   2.5 -1.   0.   0. ]
 [ 0.   0.  -1.   2.5 -1.   0. ]
 [ 0.   0.   0.  -1.   2.5 -1. ]
 [ 0.   0.   0.   0.  -1.   2.5]]
3.0 4.0080869578433
[[ 3. -1.  0.  0.  0.  0.]
 [-1.  3. -1.  0.  0.  0.]
 [

In [11]:
import numpy as np

def tridiag_toeplitz(n, a, b=-1.0):
    A = np.zeros((n, n))
    i = np.arange(n)
    A[i, i] = a
    A[i[1:], i[:-1]] = b
    A[i[:-1], i[1:]] = b
    return A

def neumann_laplacian(n):
    A = np.zeros((n, n))
    A[0,0] = 1.0
    A[-1,-1] = 1.0
    A[np.arange(1,n-1), np.arange(1,n-1)] = 2.0
    i = np.arange(n-1)
    A[i, i+1] = -1.0
    A[i+1, i] = -1.0
    return A

def cond2_spd(A):
    w = np.linalg.eigvalsh(A)
    print("eigen:", w)
    return float(w.max() / w.min())

n = 6
c = 2*np.cos(np.pi/(n+1))
for delta in [100.0, 1.0, 0.5, 1e-1, 1e-2, 1e-4, 1e-6, 1e-8]:
    A = tridiag_toeplitz(n, a=c+delta, b=-1.0)
    print(f"delta={delta:>8}, kappa2={cond2_spd(A):.3e}")
    print(A)

#for eps in [1e-2, 1e-4, 1e-6]:
#    A = neumann_laplacian(n) + eps*np.eye(n)
#    print(f"eps  ={eps:>8}, kappa2={cond2_spd(A):.3e}")

eigen: [100.         100.55495813 101.35689587 102.2469796  103.04891734
 103.60387547]
delta=   100.0, kappa2=1.036e+00
[[101.80193774  -1.           0.           0.           0.
    0.        ]
 [ -1.         101.80193774  -1.           0.           0.
    0.        ]
 [  0.          -1.         101.80193774  -1.           0.
    0.        ]
 [  0.           0.          -1.         101.80193774  -1.
    0.        ]
 [  0.           0.           0.          -1.         101.80193774
   -1.        ]
 [  0.           0.           0.           0.          -1.
  101.80193774]]
eigen: [1.         1.55495813 2.35689587 3.2469796  4.04891734 4.60387547]
delta=     1.0, kappa2=4.604e+00
[[ 2.80193774 -1.          0.          0.          0.          0.        ]
 [-1.          2.80193774 -1.          0.          0.          0.        ]
 [ 0.         -1.          2.80193774 -1.          0.          0.        ]
 [ 0.          0.         -1.          2.80193774 -1.          0.        ]
 [ 0.       